name: Android CI

on:
  push:
    branches:
      - 'master'
      - 'rework-rclone-build-action'
  pull_request:
    branches-ignore:
      - 'master'

jobs:
  build-all:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Go 1.20
      uses: actions/setup-go@v1
      with:
        go-version: 1.20
      id: go
    - name: Install NDK
      run: |
        NDK_VERSION="$(grep -E "^de\.felixnuesse\.extract\.ndkVersion=" gradle.properties | cut -d'=' -f2)"
        yes | sudo "${ANDROID_HOME}/tools/bin/sdkmanager" --licenses
        sudo "${ANDROID_HOME}/tools/bin/sdkmanager" "ndk;${NDK_VERSION}"
    - name: Build app
      run: ./gradlew assembleOssDebug
    - name: Upload APK (arm)
      uses: actions/upload-artifact@v2
      with:
        name: arm.apk
        path: app/build/outputs/apk/oss/debug/app-oss-armeabi-v7a-debug.apk
        retention-days: 3
    - name: Upload APK (arm64)
      uses: actions/upload-artifact@v2
      with:
        name: arm64.apk
        path: app/build/outputs/apk/oss/debug/app-oss-arm64-v8a-debug.apk
        retention-days: 3
    - name: Upload APK (x86)
      uses: actions/upload-artifact@v2
      with:
        name: x86.apk
        path: app/build/outputs/apk/oss/debug/app-oss-x86-debug.apk
        retention-days: 3
    - name: Upload APK (arm)
      uses: actions/upload-artifact@v2
      with:
        name: x64.apk
        path: app/build/outputs/apk/oss/debug/app-oss-x86_64-debug.apk
        retention-days: 3
    - name: Upload APK (universal)
      uses: actions/upload-artifact@v2
      with:
        name: universal.apk
        path: app/build/outputs/apk/oss/debug/app-oss-universal-debug.apk
        retention-days: 14
