name: Android CI

env:
  NDK_VERSION: "21.3.6528147"

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches-ignore:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VERSION}"
    - name: Configure local.properties
      run: |
        echo "sdk.dir=${ANDROID_HOME}" >> local.properties
        echo "ndk.dir=${ANDROID_HOME}/ndk/${NDK_VERSION}" >> local.properties
    - name: Build app
      run: ./gradlew assembleOssDebug
    - name: Upload APK
      uses: actions/upload-artifact@v2-preview
      with:
        name: universal.apk
        path: app/build/outputs/apk/oss/debug/app-oss-universal-debug.apk
